### ISSUE TITLE
I need a help

### ISSUE THREAD

**Issue by alifarooq9** [chuihairu/H610-i5-12400F-RX5600XT-Hackintosh#2]
I am currently using hackintosh (Macos Sonoma), which I just copied EFI from [here](https://www.olarila.com/topic/25111-hackintosh-efi-folders-with-opencore-mod/)

**Current Hardware**:
- i5 3570
- AMD Rx 570
- 8GB RAM
- Lexar 256GB SATA SSD

I am thinking about upgrading my hardware to:
- i5 12400f
- MSI PRO H610M-E
- 16GB Lexar DDR4-3200 ***(Should I go with DDR4 or DDR5?)***
- Lexar NM620 M.2 2280 NVMe SSD 1TB
- Same GPU

I am clueless if Macos Sonoma and latest will work on this or not, will sonoma work on this? will it work from your EFI? and if not what hardware should I get?

**Comment by cuihairu** [comment]
[https://github.com/cuihairu/MSI-PRO-H610M-E-i3-12100F-RX580-Hackintosh](https://github.com/cuihairu/MSI-PRO-H610M-E-i3-12100F-RX580-Hackintosh)
Here's an EFI for a computer configuration similar to yours.
In theory, you could just use this EFI configuration.
The current EFI configuration was tested only for Ventura.
You can try this EFI configuration, and if you encounter any errors, you can go to this repository's corresponding issues for help.

**Comment by alifarooq9** [comment]
> https://github.com/cuihairu/MSI-PRO-H610M-E-i3-12100F-RX580-Hackintosh Here's an EFI for a computer configuration similar to yours. In theory, you could just use this EFI configuration. The current EFI configuration was tested only for Ventura. You can try this EFI configuration, and if you encounter any errors, you can go to this repository's corresponding issues for help.

Thanks for the help, I will buy this hardware and will let you know it went.
